completed required document updates for issue 29
lordmauve/pgzero pull request #90
Opened 2018-07-28 13:03 UTC by MarkAColes

can you please review my updates to make sure you are happy with them before full merge?

2018-07-28 13:35 UTC, lordmauve requested changes
Thanks for this!

Just requesting a couple of styling changes - and I think replacing 1.0 with 1 loses some information (that you can pass floats). 

Good work :+1:

2018-07-28 13:35 UTC, lordmauve commented on doc/introduction.rst
> +Your Functions draw() and update() work in similar ways but are designed for two different purposes.
"functions" should be lowercase.

Please put double-backticks "``" around `draw()` and `update()` so that they appear as code.

2018-07-28 13:35 UTC, lordmauve commented on doc/introduction.rst
> +        clock.schedule_unique(set_alien_normal, 1)
Let's change this to 0.5 as it suggests in #29. 1 will work, of course, but time is a floating point quantity :)

2018-07-28 13:57 UTC, MarkAColes commented
Changes made that were advised.

2018-07-29 09:16 UTC, lordmauve commented on doc/introduction.rst
> +Your functions ''draw()'' and ''update()'' work in similar ways but are designed for two different purposes.
These should be backticks (`).

2018-07-29 09:39 UTC, MarkAColes commented
Changes made to use ` instead of '

2018-07-29 10:38 UTC, merged

2018-07-29 10:38 UTC, lordmauve commented
Thank you!